#! /usr/bin/bash

>&2 echo off=$1 on=$2

show=1
off="${1}"
on="${2}"

while read -r line; do
  [[ "${line}" =~ ${off} ]] && show=0     
  [[ "${line}" =~ ${on}  ]] && show=1
  [[ "${show}" == "1" ]]    && echo "${line}"
done
