#! /usr/bin/env zsh

show=1
off="${1:-zxcv_zakp_}"
on="${2:-zxcv_zakp_}"

while read -r line; do
  [[ "${line}" =~ "${off}" ]] && show=0
  [[ "${show}" == "1" ]] && echo "${line}"
  [[ "${line}" =~ "${on}"  ]] && show=1
done
